openapi: 3.0.0
info:
  title: Animal Forest Coding API
  description: Backend API for the Java learning platform
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
    description: Local Development Server
paths:
  /missions:
    get:
      summary: List all missions
      responses:
        '200':
          description: A JSON array of missions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mission'
  /code/execute:
    post:
      summary: Execute Java Code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                missionId:
                  type: string
      responses:
        '200':
          description: Execution result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
components:
  schemas:
    Mission:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    ExecutionResult:
      type: object
      properties:
        success:
          type: boolean
        output:
          type: string
